<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>KimJaeYoung</Authors>
    <Company>KimJaeYoung Home</Company>
	<Version>1.0.0.1</Version>
	<AssemblyVersion>1.0.0.2</AssemblyVersion>
	<FileVersion>1.0.0.3</FileVersion>
	<Title>$(AssemblyName)</Title>
	<PackageProjectUrl>https://github.com/kjyoffice/OneFileEncryptDecrypt</PackageProjectUrl>
	<RepositoryUrl>https://github.com/kjyoffice/OneFileEncryptDecrypt</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
